### ISSUE TITLE
Using text prompt for background condition

### ISSUE THREAD

**Issue by ShenZheng2000** [Haian-Jin/Neural_Gaffer#11]
In your webpage, I noticed that the last two columns use text prompts instead of environment maps as the background condition (see the attached file below).

![image](https://github.com/user-attachments/assets/dde47a79-90bf-4af5-9aba-ccfcae1f2d82)

Could you please clarify:

(1) Which part of the code should I modify to support text prompts?
(2) What command should I run to achieve this functionality?

**Comment by Haian-Jin** [comment]
Hi, we mentioned this in the paper:
<img width="798" alt="image" src="https://github.com/user-attachments/assets/e1c8df22-8ed6-4720-8cd2-e30c6f400615" />
In short, you can run Text2Light (SIGGRAPH Asia 2022) to generate environment maps from texts prompts and then use our current code to relight the input image with the generated hdr environment maps.

**Comment by ShenZheng2000** [comment]
Thanks!
