### ISSUE TITLE
relighting by own dataset

### ISSUE THREAD

**Issue by serizawa-04013958** [Haian-Jin/Neural_Gaffer#5]
Thank you for your work!
is it possible to relight by own background images?
I hope you will release code which treat wild dataset(preprocess code).

**Comment by Haian-Jin** [comment]
Hi. What do you mean when you say 'own background images'?
The diffusion model takes an environment map as the lighting condition by default.

**Comment by serizawa-04013958** [comment]
Hello, thank you for your replying.
I mean I want to use my own image as background.
Is it possible? should we need to prepare panoramic view image like below image?


![image](https://github.com/user-attachments/assets/2908dbca-885a-4fc6-8834-4a51c6387aaf)

**Comment by Haian-Jin** [comment]
Hi, our model is not conditioned on the background image.
For your requirement, I would suggest you take a look at IC-Light:
https://github.com/lllyasviel/IC-Light
