### ISSUE TITLE
License request 

### ISSUE THREAD

**Issue by YasheshSavani** [Haian-Jin/Neural_Gaffer#7]
Hello authors,

Thank you for the wonderful work. 

I would like to use your repository for research purposes but it doesn't have any license (i.e. MIT) associated with it. This creates a problem for me to use your repository legally.

Would it be possible for you to add a public use license to your repository so we (people who needs legal license to clone) can use your work?

Thank you

**Comment by Haian-Jin** [comment]
Thanks for your interest. I just added a MIT license.
